### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by DEWaller** [FNCSoftware/SharedWebComponentsMef#1]
The following components are missing in the SharedWebComponents project;

System.Composition.AttributedModel
System.Composition.Convention
System.Composition.Hosting
System.Composition.Runtime
System.Composition.TypedParts

**Comment by Micha4711** [comment]
I had the same issue today building SharedWebComponentsMef. Microsoft.Composition (which hosts the System.Composition namespace) should be installed via NuGet package restore, but NuGet threw an error on installation. I had to set the references manually. This seems to be a NuGet issue.

**Comment by p10tyr** [comment]
Same for me. I had to remove the broken references, uninstall MEF2, then reinstall it. The references added back instantly and the project built.

**Comment by drmcclelland** [comment]
Thanks!  This was the first problem I encountered, and @Micha4711 and @ppumkin had already solved it   :-)
